name: kem-test 
base: core22
version: '1.0'
summary: Test consumer snap 
description: |
  Test consumer snap

grade: stable
confinement: strict

lint:
  ignore:
    - classic 
    - library

parts:
  kem-test:
    plugin: dump
    source: .
    build-packages: 
      - openjdk-21-jdk
    override-build: |
      git clone https://github.com/openssl/openssl && cd openssl
      git checkout openssl-3.0.2
      ./Configure enable-fips && make && sudo make install && sudo make install_fips
      javac KEMTest.java
      jar -cf KEMTest.jar ./KEMTest.class 
      mkdir -p $SNAPCRAFT_PART_INSTALL/bin
      mv KEMTest.jar $SNAPCRAFT_PART_INSTALL/bin/
    stage-packages:
      - openjdk-21-jdk
      - build-essential


apps:
  kem-test:
    command: /usr/lib/jvm/java-21-openjdk-amd64/bin/java -cp $SNAP/bin/KEMTest.jar:$SNAP/imported-libs/jar/openssl-fips-java-0.0.1.jar KEMTest
    environment:
      JAVA_HOME: $SNAP/usr/lib/jvm/java-21-openjdk-amd64
      PATH: $JAVA_HOME/bin:$PATH
    plugs:
    - openssl-fips-provider-jar 

plugs:
  openssl-fips-provider-jar:
    interface: content
    content: openssl-fips-provider-jar 
    target: $SNAP/imported-libs
